@extends('layouts.master')
@extends('layouts.navbar')
@section('content')
    <div>{{$movie->title}}</div>
    <div>{{$movie->genre}}</div>
    <div>{{$movie->director}}</div>
    <div>{{$movie->production_year}}</div>
    <div>{{$movie->storyline}}</div>
@endsection